import React from 'react'
import ScrollableAnchor from 'react-scrollable-anchor'

const HeadlineProject = props => {
  return(
    <ScrollableAnchor id="headline-project">
      <div className="headline-project">
        <h3 className="research-header">Dissertation</h3>
        <img src="http://res.cloudinary.com/dpuzgzqir/image/upload/v1508803342/Waitress_with_Silk_Stockings_1933_Dorothea_Lange_qt0bjh.png" className="float-left"/>
        <p className="research-paragraph">
          My project, “Arrestable Behavior: Women, Police Power, and the Making of Law-and-Order America,” connects two seemingly contradictory trends that emerged across the twentieth century: the gradual liberalization of sexual prohibitions and the mounting force of a racially charged program of morals policing. “Arrestable Behavior” begins in the 1930s, when over one-third of all women arrested in the U.S. were charged with morals law violations—including disorderly conduct, vagrancy, and prostitution—and the bulk of these women were white. It ends in the 1980s, when morals misdemeanors accounted for only ten percent of all women’s arrests, but were overwhelmingly deployed against black women. In this work, I ask: why, as women overall became a shrinking target of sexual policing, were black women increasingly subject to morals law enforcement? By illuminating both the racial dimension of sexual liberalism and the gender dimension of policing in black neighborhoods, “Arrestable Behavior” illustrates the decisive role that race, gender, and sexuality played in the construction of contemporary urban police regimes.<br/><br/>
          Throughout this period, police officers were empowered with tremendous discretion to determine which woman they observed walking, talking, and socializing on city streets was a sexual offender. A police officer did not have to witness any particular act to make an arrest. The only evidence typically required to convict women of these morals misdemeanors was police testimony based on a subjective term of art: an observed woman’s “arrestable behavior.” That shorthand constituted a vague metric of sexual criminality drawn from the officer’s appraisal of a woman’s racial and class appearance, reputation, the company she allegedly kept, and the neighborhood in which she was apprehended. As a result, all sorts of women’s sexual and social choices—or circumstances—were gathered under the legal category of women’s sexual crime. The uniquely discretionary, police-driven enforcement of morals laws vividly demonstrates how upheavals in racial and sexual politics across the twentieth century remade white and black women as policed subjects.<br/><br/>
          I argue that across the twentieth century, the racial function of women’s sexual criminalization changed: from the moral restoration of white womanhood to the disciplinary policing of black womanhood. This shift was a powerful yet understudied driver of law-and-order policing, which is associated primarily with the targeting of black men in the War on Drugs. “Arrestable Behavior” narrates the changing racial and gendered meanings of sexual criminality through an analysis of legal reforms; institutional changes in police departments; and political contests among policewomen, police leaders, feminists, and black city residents. Ultimately, as white women’s nonmarital heterosexual practices were gradually decriminalized in the postwar decades, the sexual policing of black women transitioned from a marginal corner of law enforcement into an aggressive everyday fixture of urban police departments.<br/><br/>
    <img src="http://res.cloudinary.com/dpuzgzqir/image/upload/v1510791987/naked_tulhgw.jpg" className="float-right"/>
    “Arrestable Behavior” unites historical themes and methodological techniques that are often considered in scholarly isolation. I put archival research methods in conversation with black feminist theory and critical race and feminist legal theories in order to show how changing racial and gendered meanings of sexual criminality shaped police practices and priorities. Despite the growing literature across disciplines on police in the United States, scholars have focused on the policing of men, whether straight men of color or predominantly white, gay men. And studies on the policing of women in America largely end prior to the Depression. Moreover, scholars have not yet applied an intersectional analysis to explore changes in law enforcement amid major transformations in the racial and sexual politics in postwar U.S. cities. By uniting the fields of urban, legal, and social history, and applying an interdisciplinary analytical lens, this project contributes a rich and understudied history to the twentieth-century U.S. literature, while also delivering urgent context for the ongoing gender- and race-specific practices of mass policing in contemporary cities.
        </p>
      </div>
    </ScrollableAnchor>
  )
}

export default HeadlineProject
